{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyM+wEvO9o56MuEJ+f/+1Cis"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","source":["**Q1. What is an exception in python? Write the difference between Exceptions and Syntax errors?**\n","\n","During the execution of a program if an event or code disrupts the normal flow of the program's instructions, that event is known as exception. In general, when a Python script encounters a situation which cannot be handled, it raises an exception and it is an object that represents an error.\n","\n","Syntax errors are the errors which is raised when there is an error in Python syntax whereas exception can also be a logical error."],"metadata":{"id":"yHlDSUbANgDm"}},{"cell_type":"markdown","source":["**Q2. What happens when an exception is not handled? Explain with an example.**\n","\n","If there is an exception while running the program, python will raise an error based on the error encountered. \n","\n","For instance, \n","\n","- try to open a file(for reading) that does not exist (FileNotFoundError)\n","\n","- try to divide a number by zero (ZeroDivisionError)\n","\n","- try to import a module that does not exist (ImportError) and so on.\n"],"metadata":{"id":"RDiTUSkBNgBU"}},{"cell_type":"markdown","source":["**Q3. Which python statements are used to catch and handle exceptions? Explain with an example.**\n","\n","Exceptions in python can be handled with the help of try and except statements. \n","\n","In try and except statement, try will first try to execute the desired code, if code run OK, the program will continue to run otherwise, to program will move to except block and run the code written in this block. "],"metadata":{"id":"G-giQoLrNf-s"}},{"cell_type":"code","source":["# example \n","try:\n","    file = open('text.txt', 'r')\n","except Exception as e:\n","    print('The file does not exist')"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"XeeVlAwkRuxj","executionInfo":{"status":"ok","timestamp":1676300546797,"user_tz":0,"elapsed":438,"user":{"displayName":"Saurabh Bhardwaj","userId":"16519378442147256210"}},"outputId":"ef0b2f0f-86a8-451c-e1d1-d7432bde931a"},"execution_count":3,"outputs":[{"output_type":"stream","name":"stdout","text":["The file does not exist\n"]}]},{"cell_type":"markdown","source":["**Q4. Explain with an example:**\n","\n","**- try and else**\n","\n","**- finally**\n","\n","**- raise** "],"metadata":{"id":"WPFTCOrbNf8W"}},{"cell_type":"code","source":["# Try and Else\n","'''\n","Try and else statement is a condition is python which is excecuted togather. Else will execute only when try is executed otherwise it won't execute.\n","'''\n","# Example \n","try:\n","    print('This is a try block')\n","except Exception as e:\n","    print('There is a problem')\n","else:\n","    print('Try has been executed')"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"Dw0kE6yyTddZ","executionInfo":{"status":"ok","timestamp":1676300782991,"user_tz":0,"elapsed":253,"user":{"displayName":"Saurabh Bhardwaj","userId":"16519378442147256210"}},"outputId":"ce4d6e72-9561-4e9c-95a4-90561f46e20c"},"execution_count":5,"outputs":[{"output_type":"stream","name":"stdout","text":["This is a try block\n","Try has been executed\n"]}]},{"cell_type":"code","source":["# finally\n","'''\n","finally is a part of exception handling in try and except statements. block of code inside finally statement will always execute irrespective to error or not.\n","'''\n","\n","# example\n","try:\n","    a = int(input())\n","except Exception as e:\n","    print('There is a problem')\n","finally:\n","    print('Try has been executed')"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"nuTp-rtTUB7F","executionInfo":{"status":"ok","timestamp":1676300913503,"user_tz":0,"elapsed":2714,"user":{"displayName":"Saurabh Bhardwaj","userId":"16519378442147256210"}},"outputId":"b9de35b2-e152-4a36-a960-4057382fda4a"},"execution_count":9,"outputs":[{"output_type":"stream","name":"stdout","text":["s\n","There is a problem\n","Try has been executed\n"]}]},{"cell_type":"code","source":["# raise\n","'''\n","The raise keyword is used to raise an exception.\n","You can define what kind of error to raise, and the text to print to the user.\n","'''\n","\n","# example\n","x = \"hello\"\n","\n","if not type(x) is int:\n","  raise TypeError(\"Only integers are allowed\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":200},"id":"XRAMG8FhUoGE","executionInfo":{"status":"error","timestamp":1676301039840,"user_tz":0,"elapsed":356,"user":{"displayName":"Saurabh Bhardwaj","userId":"16519378442147256210"}},"outputId":"64755f5b-90ba-4083-e404-9d181652bc77"},"execution_count":10,"outputs":[{"output_type":"error","ename":"TypeError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-10-15d40ad77c53>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      9\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     10\u001b[0m \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mtype\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mx\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0mint\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 11\u001b[0;31m   \u001b[0;32mraise\u001b[0m \u001b[0mTypeError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Only integers are allowed\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mTypeError\u001b[0m: Only integers are allowed"]}]},{"cell_type":"markdown","source":["**Q5. What are Custom Exceptions in python? Why do we need Custome Exceptions? Explain with an example.**\n","\n","in python, sometimes we may need to create our own custom exceptions that serve our purpose. Custom exception are similar to python exception but it is customise to raise a specific information as per user requirements. \n","\n","We can define custom exceptions by creating a new class that is derived from the built-in Exception class.\n","\n","For instance, if we want user to enter his or her age. We can raise custom excpetion based on pre-defined criterion such as age must be a positive integer and should not be greater than 150 etc. "],"metadata":{"id":"8MKM666TNf6W"}},{"cell_type":"markdown","source":["**Q6. Create a custom exception class. use this class to handle an exception.**"],"metadata":{"id":"BDEeHzEYNf3M"}},{"cell_type":"code","source":["# example \n","\n","# define user-defined exceptions\n","class InvalidAgeException(Exception):\n","    \"Raised when the input value is less than 18\"\n","    pass\n","\n","# you need to guess this number\n","age = 18\n","\n","try:\n","    input_num = int(input(\"Enter a number: \"))\n","    if input_num < age:\n","        raise InvalidAgeException\n","    else:\n","        print(\"Eligible to Vote\")\n","        \n","except InvalidAgeException:\n","    print(\"Exception occurred: Invalid Age\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"_6uyMFQJVBnD","executionInfo":{"status":"ok","timestamp":1676304198132,"user_tz":0,"elapsed":4003,"user":{"displayName":"Saurabh Bhardwaj","userId":"16519378442147256210"}},"outputId":"901d7c70-3e24-48e3-f8a5-803ecb8d398b"},"execution_count":11,"outputs":[{"output_type":"stream","name":"stdout","text":["Enter a number: 3\n","Exception occurred: Invalid Age\n"]}]},{"cell_type":"code","source":[],"metadata":{"id":"i1C_p1_jhBgt"},"execution_count":null,"outputs":[]}]}